# Generated by Django 5.2.3 on 2025-06-22 09:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Логин должен содержать только кириллицу (не менее 6 символов)', regex='^[а-яА-ЯёЁ]{6,}$')], verbose_name='Логин')),
                ('full_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Только кириллические символы и пробелы', regex='^[А-Яа-яЁё\\s]+$')], verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Формат: +7(XXX)-XXX-XX-XX', regex='^\\+7\\(\\d{3}\\)-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transport_date', models.DateTimeField(verbose_name='Дата и время перевозки')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес груза')),
                ('dimensions', models.CharField(max_length=100, verbose_name='Габариты')),
                ('from_address', models.TextField(verbose_name='Адрес отправления')),
                ('to_address', models.TextField(verbose_name='Адрес доставки')),
                ('cargo_type', models.CharField(choices=[('large', 'Крупное'), ('perishable', 'Скоропортящееся'), ('refrigerated', 'Требуется рефрижератор'), ('animals', 'Животные'), ('liquid', 'Жидкость'), ('furniture', 'Мебель'), ('waste', 'Мусор')], max_length=20, verbose_name='Тип груза')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('cancelled', 'Отменена')], default='new', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
